<a href="https://colab.research.google.com/github/holmon-alp/mohirdev-numpy/blob/main/mohirdev_NumPy_holmon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np
print(
    np.version,
    np.show_config()
)

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [2]:
arr = np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [3]:
zeros = np.zeros(9)
zeros # agar 9D arrayni nazarda tutgan bo'lsangiz xotiraga sig'madi

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [4]:
arr = np.arange(1, 11)
memory_size = arr.size * arr.itemsize
memory_size

80

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [5]:
np.info('add')

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [90]:
arr = np.zeros(12)
arr[5] = 1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [7]:
arr = np.arange(20, 60)
arr

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [8]:
arr = np.arange(10)
reversed_arr = arr[::-1]
reversed_arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [9]:
arr3x3 = np.arange(12, 21).reshape(3, 3)
arr3x3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [10]:
arr = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(arr)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [11]:
rand_array = np.random.randn(2,2,2)
rand_array

array([[[-0.51058115, -1.47389644],
        [-1.24285973,  1.12390309]],

       [[ 0.08036412,  2.03346774],
        [ 1.34636497, -2.59828788]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [13]:
rand_array = np.random.randn(9,9)
print(
    rand_array,
    rand_array.min(),
    rand_array.max(),
    sep='\n\n'
)

[[-0.26867261  0.61439481 -0.29656794  0.08742509  1.24202483 -0.93717501
   0.11650216  0.28374362  1.56656087]
 [-0.60339227  2.40269597  0.22101345 -1.21137366  0.85515437 -0.11979469
   0.89555553  0.08244022  0.19140441]
 [-0.76674495  0.19030054  1.05844529 -0.79668245 -0.15464253 -0.59851796
   1.42647746 -0.42651159 -0.53288461]
 [-0.13137559  0.83696977  1.08751162 -0.53224902 -0.81388213 -0.59545859
   0.23931212  1.69347156 -0.44563337]
 [-0.28110541 -0.73769826 -0.99018381  0.3168099  -0.69656576 -0.22256716
   1.90683808 -0.58571567  0.15585519]
 [-2.36509548  0.34000895  1.01095994  0.70258623 -1.83633568  0.28570868
   1.30200964 -1.23253065  0.44410175]
 [ 0.05432032  1.39213174 -0.60665529  0.89053552 -0.52459341 -1.07361279
  -0.22717235  0.65311597  0.44830768]
 [-1.75110954 -0.75791366 -0.27030682  1.01661328  1.92634216 -1.18821532
  -0.99382428 -0.63282564 -0.80332942]
 [-1.01326003 -1.47382083 -1.1020193   0.25162389  1.37380273  0.86261341
  -1.99960449 -0.12287

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [14]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [17]:
a = np.random.randn(6,3)
b = np.random.randn(3,4)
# np.dot(a, b)
# a @ b
a.dot(b)

array([[-0.59758415,  3.03308934,  1.26966136,  6.02181347],
       [ 0.25508199, -0.54199534, -0.47405361, -1.31035172],
       [ 0.88163212,  0.76350888, -1.16772587,  0.44309088],
       [-0.17267706,  0.39170333,  0.04640307,  0.26563895],
       [ 0.2349996 ,  4.53953123, -1.09923963,  4.5524275 ],
       [ 1.28987145, -1.17896232, -1.39070257, -1.93818426]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [18]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [19]:
a = np.array([1,2])
b = np.array([4,5])
print(
    a > b,
    a >= b,
    a < b,
    a <= b,
    sep='\n'
)

[False False]
[False False]
[ True  True]
[ True  True]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [20]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-20-cd809174da5d>:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
<ipython-input-20-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [21]:
a = np.arange(2, 20, 3)
b = np.arange(3, 20, 2)
np.intersect1d(a, b)

array([ 5, 11, 17])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [29]:
a = np.random.randn(10)
print(
    a - (a % 1), # array elementlaridan kasr qismini ayirib tashlash
    np.floor(a), # bu method katta tarafdan butunga yaxlitlaydi
    a.astype(int), # bu method int tipiga konvertatsiya qiladi
    np.trunc(a), # bu method butun qismini olib kasr qismini tashlab yuboradi
    sep='\n'
)

[-1.  0.  0.  0. -1.  0. -1.  0.  1. -1.]
[-1.  0.  0.  0. -1.  0. -1.  0.  1. -1.]
[0 0 0 0 0 0 0 0 1 0]
[-0.  0.  0.  0. -0.  0. -0.  0.  1. -0.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [30]:
matritsa = np.random.randint(0, 3, size=(3, 3))
matritsa

array([[1, 2, 0],
       [2, 1, 2],
       [2, 1, 2]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [35]:
vektor = np.random.randn(10)
# np.sort(vektor)
vektor.sort()
vektor

array([-1.91935548, -1.71236482, -1.076116  , -0.90060746, -0.86603957,
        0.06810991,  0.12279803,  0.3123445 ,  0.58560223,  1.07658164])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [37]:
A = np.random.randn(10)
B = np.random.random(10)
# np.allclose(A, B)
np.array_equal(A, B)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [41]:
a = np.random.randn(6, 3)
b = np.random.randn(3, 4)
# np.dot(a, b)
# a @ b
a.dot(b)

array([[ 1.11472952,  0.9357128 ,  0.76448831,  0.81114258],
       [-1.83902486,  0.61783052,  3.91898934, -2.30819625],
       [-1.01159415, -2.02215276, -0.49827121, -1.81118009],
       [-0.01028286,  2.32635022,  0.81143488,  1.48933301],
       [ 0.9563119 , -1.4058851 , -2.53269963,  0.56604848],
       [-0.8335899 ,  1.31433151, -0.10747547,  0.81330483]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [44]:
vektor = np.random.random(5)
print(vektor)
# vektor[vektor == vektor.max()] = 0
vektor[vektor.argmax()] = 0
vektor

[0.40226709 0.26389343 0.64750065 0.65655833 0.54448931]


array([0.40226709, 0.26389343, 0.64750065, 0.        , 0.54448931])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [49]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(
    f"""
    yesterday:{yesterday};
    today:{today};
    tomorrow:{tomorrow}
    """
)


    yesterday:2023-11-11;
    today:2023-11-12;
    tomorrow:2023-11-13    
    


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [51]:
january1 = np.datetime64('2016-01-01')
january31 = np.datetime64('2016-01-31') + np.timedelta64(1, 'D')
calendar = np.arange(january1, january31, dtype='datetime64[D]')
calendar

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [52]:
# Bu savol yuqorida takrorlangan
a = np.random.randn(10)
print(
    a - (a % 1), # array elementlaridan kasr qismini ayirib tashlash
    np.floor(a), # bu method katta tarafdan butunga yaxlitlaydi
    a.astype(int), # bu method int tipiga konvertatsiya qiladi
    np.trunc(a), # bu method butun qismini olib kasr qismini tashlab yuboradi
    sep='\n'
)

[ 0. -1.  1.  0. -1.  0. -1. -1.  0.  1.]
[ 0. -1.  1.  0. -1.  0. -1. -1.  0.  1.]
[0 0 1 0 0 0 0 0 0 1]
[ 0. -0.  1.  0. -0.  0. -0. -0.  0.  1.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [53]:
massiv = np.arange(1, 10)
np.add.reduce(massiv)

45

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [55]:
array = np.array( [1, 2, 3, 4, 5] )
zeros = np.zeros(len(array)*4, dtype=int) # arraydan 4 marta katta boshqa zeros array
zeros[::4] = array # elementlar orasiga birinchi array elementlarini joylash
zeros

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0])

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [58]:
from numpy.lib.stride_tricks import as_strided
a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
array = np.array(a)
strides = array.strides[0]

new = as_strided(array, shape=(len(array)-3, 4), strides=(strides, strides))
new

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [84]:
array = np.random.randint(0, 5, size=(10))
takrorlangan = np.bincount(array)
takrorlangan = takrorlangan[takrorlangan > 1]
takrorlangan

array([2, 2, 4])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

**Numpy** yordamida shu yil joriy sana kuni va o'zingizni tug'ilgan kuningizni oling, keyin ikki sana orasidagi farqni toping.

In [89]:
current_date = np.datetime64('today')

birthday = np.datetime64('2003-01-18')
difference = current_date - birthday

print("Joriy Sana:", current_date)
print("Tug'ilgan Kunim:", birthday)
print("Sana Orasidagi Farq:", difference)


Joriy Sana: 2023-11-12
Tug'ilgan Kunim: 2003-01-18
Sana Orasidagi Farq: 7603 days
